// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAneWNUJ-NHUBl9K5DdpsoOHNSdaXz_OQg',
    appId: '1:425124565931:web:5bc2712a28ef76d8aff8ee',
    messagingSenderId: '425124565931',
    projectId: 'negotiationapp-1701d',
    authDomain: 'negotiationapp-1701d.firebaseapp.com',
    storageBucket: 'negotiationapp-1701d.appspot.com',
    measurementId: 'G-G9GQWD7QMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaX8DQEnMXnU8s2MZtJ5lRtHiRKsMnRuI',
    appId: '1:425124565931:android:bb429c111bc47bf8aff8ee',
    messagingSenderId: '425124565931',
    projectId: 'negotiationapp-1701d',
    storageBucket: 'negotiationapp-1701d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaQSfLMYwPf8QQP3Wh2k94xsh_Ls_Mmwc',
    appId: '1:425124565931:ios:a950a95373c37d7daff8ee',
    messagingSenderId: '425124565931',
    projectId: 'negotiationapp-1701d',
    storageBucket: 'negotiationapp-1701d.appspot.com',
    iosClientId: '425124565931-vg0tjb76o2ahkdrrrn4c4b2srad6irrb.apps.googleusercontent.com',
    iosBundleId: 'com.spaghetticodeinc.negotiationTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaQSfLMYwPf8QQP3Wh2k94xsh_Ls_Mmwc',
    appId: '1:425124565931:ios:a950a95373c37d7daff8ee',
    messagingSenderId: '425124565931',
    projectId: 'negotiationapp-1701d',
    storageBucket: 'negotiationapp-1701d.appspot.com',
    iosClientId: '425124565931-vg0tjb76o2ahkdrrrn4c4b2srad6irrb.apps.googleusercontent.com',
    iosBundleId: 'com.spaghetticodeinc.negotiationTracker',
  );
}
